{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-metrics
  labels: 
    {{- include "common.labels.standard" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "flyway-operator.selectorLabels" . | nindent 4 }}
{{- end }}
