# permissions for end users to edit migrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  name: migration-editor-role
rules:
- apiGroups:
  - flyway.davidkarlsen.com
  resources:
  - migrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flyway.davidkarlsen.com
  resources:
  - migrations/status
  verbs:
  - get
