apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flyway-operator
    app.kubernetes.io/part-of: flyway-operator
    control-plane: controller-manager
  name: flyway-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/part-of: flyway-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
