apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "flyway.davidkarlsen.com/v1alpha1",
          "kind": "Migration",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "flyway-operator",
              "app.kubernetes.io/instance": "migration-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "migration",
              "app.kubernetes.io/part-of": "flyway-operator"
            },
            "name": "migration-sample",
            "namespace": "test"
          },
          "spec": {
            "database": {
              "credentials": {
                "key": "password",
                "name": "migration-pw"
              },
              "jdbcUrl": "jdbc:db2://somehost:50000/devdb",
              "username": "db2inst1"
            },
            "migrationSource": {
              "imageRef": "ghcr.io/davidkarlsen/testmigration:latest"
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Database,Developer Tools
    createdAt: "2025-10-14T23:19:42Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: flyway-operator.v0.0.9
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Migration is the Schema for the migrations API
      displayName: Migration
      kind: Migration
      name: migrations.flyway.davidkarlsen.com
      version: v1alpha1
  description: Run Flyway through declarative API.
  displayName: Flyway Operator
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDIwIiBoZWlnaHQ9Ijk3MCIgdmlld0JveD0iMCAwIDEwMjAgOTcwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2MwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkZseXdheTwvdGl0bGU+PHBhdGggZD0iTTMuOSw4OTguM0MwLDg4NS42LDAsODczLjQsMCw4NjAuNVY3NjQuMkMwLDczMS42LjYsNjk0LjUsOC4yLDY2M2MyOC02LjksNTkuOC03LjMsOTMuMi03LjNoNzIuOWE3Ni45LDc2LjksMCwwLDEsMS43LDE1LjIsODYuNyw4Ni43LDAsMCwxLTEuNywxNS4yYy0xMC4yLDMuMy0yMC40LDMuMy0zMC45LDMuM0gxMDNjLTIxLjgsMC00MC43LDAtNTkuNSwzLjktMi43LDIwLjEtMy4zLDQ0LTMuMyw3MUgxNDkuNGE2Mi42LDYyLjYsMCwwLDEsMS42LDE0LjksNzMuNyw3My43LDAsMCwxLTEuNiwxNS43Yy0xMC41LDMuMy0yMC40LDMuMy0zMS42LDMuM0g0MC4ydjEwMGE4MS44LDgxLjgsMCwwLDEtMTcuNywxLjdBMTUwLjgsMTUwLjgsMCwwLDEsMy45LDg5OC4zWiIvPjxwYXRoIGQ9Ik0xOTkuOSw4OThhMjM0LjQsMjM0LjQsMCwwLDEtMS45LTMzLjVWNjg5LjZjMC0xMS42LDAtMjMsMy42LTM0LjNhNzQsNzQsMCwwLDEsMzAuNiwwYzMuMywxMS4yLDMuMywyMywzLjMsMzQuNlY4NjQuMWMwLDEwLjguMywyMS4xLTIsMzMuOWE1OS43LDU5LjcsMCwwLDEtMTYuMSwyQTcyLjgsNzIuOCwwLDAsMSwxOTkuOSw4OThaIi8+PHBhdGggZD0iTTI3My4yLDk2Ny43bDMzLjItNzUuOUwyNTkuOCw3NzguN2MtNS4yLTEzLjEtMTMuMi0zMS4yLTEzLjUtNDUuNmE2OS4yLDY5LjIsMCwwLDEsMTguOC0yLjMsNzAsNzAsMCwwLDEsMTcuNywybDQ0LDExNC43LDIzLjgtNTEuOWM3LjUtMTYuOSwxNy43LTQ0LjgsMjIuNi02Mi44YTc3LjIsNzcuMiwwLDAsMSwxOC41LTIsNzQuMSw3NC4xLDAsMCwxLDE4LDJjLTIuMiwyMS0xNC4xLDQ1LjYtMjYuMyw3My4zTDMxMyw5NjcuN2E4OS4zLDg5LjMsMCwwLDEtMTkuNCwyQTk0LjEsOTQuMSwwLDAsMSwyNzMuMiw5NjcuN1oiLz48cGF0aCBkPSJNNDU3LjgsODk4LDQyMy45LDc3MS4xYy00LTE0LjQtNy42LTI3LjYtOC4zLTM4LjFhODYuOCw4Ni44LDAsMCwxLDIwLjQtMi4zLDg1LjgsODUuOCwwLDAsMSwxOC44LDJsMjkuNiwxMjYuOUw1MzAuOCw3MzRhNjcsNjcsMCwwLDEsMTUuMS0xLjdBNzQuOCw3NC44LDAsMCwxLDU2Miw3MzRsNDYuNCwxMjUuNiwyOS41LTEyNi45YTgwLjcsODAuNywwLDAsMSwxOC41LTIsODcuNiw4Ny42LDAsMCwxLDIwLjcsMi4zYy0xLDEyLjEtNC4yLDI0LjktOCwzOC40TDYzNi4zLDg5OGMtOS4yLDIuMy0xNi4xLDMuMy0yMi43LDMuM3MtMTQuMi0xLTI0LjQtMy4zTDU0Ni40LDc4My45LDUwNC43LDg5OGMtOS41LDIuMy0xNi4xLDMuMy0yMywzLjNTNDY3LjksOTAwLjQsNDU3LjgsODk4WiIvPjxwYXRoIGQ9Ik02OTIuNSw4NDQuNFY4MzEuNmMwLTI0LjksMS4xLTY0LjQsMTEuNi04OS41LDI0LjMtMTEuOCw0NS4xLTE3LjEsNjQuNy0xNy4xLDQyLjQsMCw3NiwxMS4yLDc2LDU3Ljl2NjkuNGEzOTcuNSwzOTcuNSwwLDAsMS0yLjYsNDUuNiw0OS4yLDQ5LjIsMCwwLDEtMTMuOSwyLDY5LjgsNjkuOCwwLDAsMS0xNi0ybC0zLTE2Yy0xMS45LDEyLjEtMzIuOSwxOS42LTU1LDE5LjZTNjkyLjUsODkyLjIsNjkyLjUsODQ0LjRaTTgwNyw4NTIuN1Y3NjYuNWMtNy41LTYuMy0yMy05LjItMzguNS05LjJzLTMxLjIsMy0zOC43LDkuMnY5Mi43YzguMiw2LjYsMTksOS41LDMwLjIsOS41Qzc3Ni40LDg2OC44LDc5NC4xLDg2Mi42LDgwNyw4NTIuN1oiLz48cGF0aCBkPSJNODgzLjYsOTY3LjdsMzMuMi03NS45TDg3MC4xLDc3OC42Yy01LjMtMTMuMi0xMy4yLTMxLjItMTMuNS00NS42YTY5LDY5LDAsMCwxLDE4LjctMi4zLDcxLjQsNzEuNCwwLDAsMSwxNy44LDJsNDQsMTE0LjcsMjMuNy01MmM3LjUtMTYuOCwxNy44LTQ0LjcsMjIuNy02Mi43YTc3LjIsNzcuMiwwLDAsMSwxOC41LTIsNzUuMyw3NS4zLDAsMCwxLDE4LDJjLTIuMywyMS0xNC4xLDQ1LjYtMjYuMyw3My4zTDkyMy40LDk2Ny43YTg5LjMsODkuMywwLDAsMS0xOS40LDJBOTQuMSw5NC4xLDAsMCwxLDg4My42LDk2Ny43WiIvPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTQyOS40LDM3NC45YTU4LjYsNTguNiwwLDAsMCw5LjUtMjguNGwtNDQuNiw5LjJhMjguMywyOC4zLDAsMCwxLTUsLjUsMjUuMSwyNS4xLDAsMCwxLTUtNDkuNmwxMDEuMi0yMC44QTYwLjIsNjAuMiwwLDAsMCw1MjMuNiwyNjBhNjEuMiw2MS4yLDAsMCwwLDkuOC0yOC43bC00NC44LDkuMmEyOC4zLDI4LjMsMCwwLDEtNSwuNUEyNSwyNSwwLDAsMSw0NTksMjIwLjhjLTIuNy0xMy42LDYuNS0yNi43LDIwLjEtMjkuNWwxMDAtMjAuNWMxOS41LTQsMzAuOS0yMCwzNi0yOS4xYTgwLjUsODAuNSwwLDAsMCw5LTI2LjNMMzA5LjUsMTgwVjQxNy44bDgwLjgtMTYuNkE2MS42LDYxLjYsMCwwLDAsNDI5LjQsMzc0LjlaIi8+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNNTEwLC4zYy04OCwwLTE2NC45LDE3LjgtMjAwLjYsNDMuNHY4NS4xTDY1NC40LDU4YTEzLjYsMTMuNiwwLDAsMSwxNiwxMC41bDIuMywxMS4zYzUuOCwyOC4zLjgsNTkuNy0xMy45LDg2LjItMTYsMjguOC00MC44LDQ3LjktNjkuOSw1My45bC01LjUsMS4xYTEwOC45LDEwOC45LDAsMCwxLTE4LjksNjcuN2MtMTYuMywyNC4yLTQxLjcsNDAuNS03MC4yLDQ2LjRsLTUuMywxLjFhMTEwLjUsMTEwLjUsMCwwLDEtODcuOCwxMTRMMzA5LjQsNDY5djIyLjhDMzQ1LjEsNTE3LjUsNDIyLDUzNS4zLDUxMCw1MzUuM3MxNjQuOS0xNy44LDIwMC42LTQzLjVWNDMuN0M2NzQuOSwxOC4xLDU5OCwuMyw1MTAsLjNaIi8+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - flyway.davidkarlsen.com
          resources:
          - migrations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - flyway.davidkarlsen.com
          resources:
          - migrations/finalizers
          verbs:
          - update
        - apiGroups:
          - flyway.davidkarlsen.com
          resources:
          - migrations/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: flyway-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: flyway-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: flyway-operator
          control-plane: controller-manager
        name: flyway-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/part-of: flyway-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/part-of: flyway-operator
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                    - {}
              containers:
              - args:
                - --leader-elect
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=:8443
                - --metrics-secure=true
                command:
                - /manager
                image: ghcr.io/davidkarlsen/flyway-operator:0.0.9
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: flyway-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: flyway-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - schema
  - versioning
  - database
  - flyway
  - migration
  links:
  - name: Flyway Operator
    url: https://github.com/davidkarlsen/flyway-operator
  maintainers:
  - email: david@davidkarlsen.com
    name: davidkarlsen
  maturity: alpha
  minKubeVersion: 1.20.0
  provider:
    name: David J. M. Karlsen
    url: https://github.com/davidkarlsen/
  version: 0.0.9
