apiVersion: v2
name: flyway-operator
description: Flyway Operator - an operator to do declarative database schema migration.
type: application
icon: https://pbs.twimg.com/profile_images/1339525060999192576/9ltj0fpE_400x400.png
version: 0.1.0
appVersion: 0.1.6
maintainers:
- name: davidkarlsen
  email: david@davidkarlsen.com
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
